import { WorkOrderData } from "../../types/work-order.types";

export const workOrderData: WorkOrderData[] = [
  {
    id: 1,
    time: "9:30 am",
    serviceType: "Hot Water Heater Replacement",
    jobNumber: "1124",
    clientFirstName: "Danny",
    clientLastName: "Thompson",
    missingParts: true,
    clientStreetAddress: "1234 Whispy Oaks Ln",
    clientCity: "Dallas",
    clientState: "TX",
    clientPostalCode: "75001",
    workOrderStatus: "complete",
    clientPrimaryPhone: "123-456-7890",
    clientSecondaryPhone: "980-765-4321",
    clientEmail: "dthompsondev@dsd.org",
    parts: [
      { name: "Water Heater Unit", qtyNeed: 1, qtyStock: 1 },
      {
        name: 'Flexible Water Supply Line, 3/4"x10"(Each)',
        qtyNeed: 2,
        qtyStock: 2,
      },
      { name: 'Dielectric Union, 3/4" (Each)', qtyNeed: 2, qtyStock: 0 },
      { name: 'Pressure Relief Valve, 3/4" (Each)', qtyNeed: 1, qtyStock: 1 },
    ],
    appointmentNotes:
      "We will need clear access to your utility area. Please move any items as needed and secure pets prior to our visit as we will be entering and exiting your home. Thanks!",
  },
  {
    id: 2,
    time: "10:30 am",
    serviceType: "Faucet Repair",
    jobNumber: "1125",
    clientFirstName: "Theodore",
    clientLastName: "Roosevelt",
    missingParts: true,
    clientStreetAddress: "2376 Rodeo Dr",
    clientCity: "Dallas",
    clientState: "TX",
    clientPostalCode: "75002",
    workOrderStatus: "pending",
    clientPrimaryPhone: "222-222-2222",
    clientSecondaryPhone: "333-333-3333",
    clientEmail: "troosevelt@usa.gov",
    parts: [
      { name: "Faucet", qtyNeed: 1, qtyStock: 1 },
      {
        name: 'Flexible Water Supply Line, 3/4"x10"(Each)',
        qtyNeed: 2,
        qtyStock: 2,
      },
      { name: "Mounting Hardware", qtyNeed: 1, qtyStock: 0 },
    ],
    appointmentNotes:
      "We will need clear access to your utility area. Please move any items as needed and secure pets prior to our visit as we will be entering and exiting your home. Thanks!",
  },
  {
    id: 3,
    time: "12:30 pm",
    serviceType: "Hose Bib Repair",
    jobNumber: "1126",
    clientFirstName: "Frances",
    clientLastName: "Henkels",
    missingParts: false,
    clientStreetAddress: "444 Green St",
    clientCity: "Dallas",
    clientState: "TX",
    clientPostalCode: "75003",
    workOrderStatus: "cancelled",
    clientPrimaryPhone: "303-303-0303",
    clientSecondaryPhone: "303-234-2344",
    clientEmail: "franceshenkels@dsd.org",
    parts: [
      { name: "Hose bib", qtyNeed: 1, qtyStock: 1 },
      {
        name: 'Flexible Water Supply Line, 3/4"x10"(Each)',
        qtyNeed: 2,
        qtyStock: 2,
      },
      { name: "Water shutoff valve", qtyNeed: 2, qtyStock: 2 },
      { name: 'Pressure Relief Valve, 3/4" (Each)', qtyNeed: 1, qtyStock: 1 },
    ],
    appointmentNotes:
      "We will need clear access to your utility area. Please move any items as needed and secure pets prior to our visit as we will be entering and exiting your home. Thanks!",
  },
];
